version: '3.8'

services:
  app:
    build: .
    container_name: study-system-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      # 如果需要持久化数据，可以挂载数据目录
      - ./data:/app/data
    networks:
      - study-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: study-system-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # 如果有SSL证书，可以挂载
      # - ./ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - study-network

networks:
  study-network:
    driver: bridge

volumes:
  app-data:
    driver: local